[package]
  cjc-version = "1.0.5"
  name = "cli"
  description = "nothing here"
  version = "0.10.0"
  target-dir = ""
  output-type = "static"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
